apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdHBhc3M=               # rootpass
  auth-password: YXV0aHBhc3M=               # authpass
  secret-key: eGNvMHNyMGZoNGU1MngwM2c5bXY=  # xco0sr0fh4e52x03g9mv